name: alchemy
description: Alchemy

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.9.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  app_links: ^6.0.1
  animations: ^2.0.10
  async: ^2.11.0
  audio_service: ^0.18.14
  audio_session: ^0.1.20
  cached_network_image: ^3.3.0
  clipboard: ^0.1.3
  collection: ^1.18.0
  connectivity_plus: ^6.0.2
  country_currency_pickers: ^3.0.0
  crypto: ^3.0.3
  custom_navigator:
    path: ./custom_navigator
  device_info_plus: ^11.1.0
  # Gradle 8 updated version:
  draggable_scrollbar: ^0.1.0
  encrypt: ^5.0.3
  envied: ^1.1.1
  # Gradle 8 updated version:
  # Gradle 8 updated version:
  external_path:
    path: ./external_path
  filesize: ^2.0.1
  fluttericon: ^2.0.0
  fluttertoast: ^8.2.4
  flutter_cache_manager: ^3.3.1
  flutter_displaymode: ^0.6.0
  #flutter_file_dialog: ^3.0.1
  flutter_inappwebview: ^6.1.0+1
  flutter_local_notifications: ^18.0.1
  flutter_markdown: ^0.7.4+3
  flutter_material_color_picker: ^1.2.0
  flutter_screenutil: ^5.9.0
  get_it: ^8.0.0
  google_fonts: ^6.1.0
  html: ^0.15.3
  http: ^1.2.1
  i18n_extension: ^15.0.4
  intl: ^0.19.0
  json_annotation: ^4.9.0
  just_audio: ^0.9.39
  #just_audio:
  #  git:
  #    url: https://github.com/ryanheise/just_audio.git
  #    ref: visualizer
  #    path: just_audio
  #just_audio_platform_interface:
  #  git:
  #    url: https://github.com/ryanheise/just_audio.git
  #    ref: visualizer
  #    path: just_audio_platform_interface
  logging: ^1.2.0
  #marquee: ^2.2.3
  marquee:
    path: ./marquee
  #move_to_background: ^1.0.1
  # Gradle 8 updated version:
  move_to_background:
    path: ./move_to_background
  numberpicker: ^2.1.2
  package_info_plus: ^8.0.0
  palette_generator: ^0.3.3+3
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pointycastle: ^3.7.4
  quick_actions: ^1.0.6
  #random_string: ^2.0.1
  #restart_app: ^1.2.1
  # Gradle 8 updated version:
  #restart_app:
  #  git:
  #    url: https://github.com/Argaros/restart_app.git
  rxdart: ^0.28.0
  scrobblenaut:
    path: ./scrobblenaut
  share_plus: ^10.0.0
  spotify: ^0.13.1
  sqflite: ^2.3.0
  url_launcher: ^6.2.2
  #version: ^3.0.2 Added contents in source directly for compatibility
  visibility_detector: ^0.4.0+2
  wakelock_plus: ^1.2.10
  lottie: ^3.1.3
  awesome_ripple_animation: ^2.0.0
  liquid_progress_indicator_v2:
    path: ./liquid_progress_indicator_v2
  figma_squircle:
    path: ./figma_squircle
  open_filex:
    path: ./open_filex

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0
  envied_generator: ^1.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/cover.jpg
    - assets/banner.png
    - assets/cover_thumb.jpg
    - assets/icon_legacy.png
    - assets/icon.png
    - assets/favorites_thumb.jpg
    - assets/browse_icon.png
    - assets/DJDoubleD.jpg
    - assets/PetitPrince.png
    - assets/chrome.png
    - assets/token.png
    - assets/deezer.png
    - assets/lrclib.png
    - assets/lyricfind.png
    - assets/animations/bubbles.json
    - assets/animations/logo_closing.json
    - assets/animations/welcome_waves.json
    - assets/animations/playing_wave.json
    - assets/animations/pausing_wave.json

  fonts:
    - family: AlchemyIcons
      fonts:
        - asset: assets/fonts/AlchemyIcons.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Extrabold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Extrabold.ttf
          weight: 900

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
